version: '3.5'
services:

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
    configs:
      - source: prometheus-yaml
        target: "/etc/prometheus/prometheus.yaml"
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "10"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - grafana:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "10"

volumes:
  grafana:

configs:
  prometheus-yaml:
    file: "./prometheus.yaml"